### PR TITLE
Liquidity page show orders

### LINKED ISSUE #989: Liquidity Orders Widget
One UX review was the lack of seeing current liquidity orders inside Liquidity page - consider adding an OrdersWidget inside to allow users to see without changing pages

Closed
Screenshot from 2020-05-02 15-24-40

Open
Screenshot from 2020-05-02 15-24-56

### PR DESCRIPTION
**Pull request by W3stside**
Closes #989 

If we want it, we can have it

1. adds Liquidity OrdersWidget to Liquidity page [only the liquidity tab]
2. modalises more the CSS/logic for OrdersWidget to facilitate moving it around
2.5: adds a loading spinner to OrderWidget orders type tab when loading the orders and getting the count - this is only triggered when loading the Active/Liquidity/Closed orders
3. minor CSS fixes that were annoying
    a. Nav menus weren't aligned before
4. refactor OrdersWidget index a bit to move OrdersTable into own comp
5. Change `<form>` inside `OrdersWidget` only responsible for removing orders into a div with onClick to avoid form within form problem from adding OrdersWidget inside of Liquidity (which also uses form)

### CODE REVIEW

**Comment by Velenir** [comment]
Why no PRaul link? Because not to `develop`? Should we change that?

**Comment by anxolin** [comment]
> Why no PRaul link? Because not to develop? Should we change that?

No, is not that. I've made yesterday a PR to Leandro's branch, and I get the PRaul

**Comment by Velenir** [comment]
> No, is not that. I've made yesterday a PR to Leandro's branch, and I get the PRaul

Wait. Travis didn't even run here. What gives? :confused:

**Comment by anxolin** [comment]
@W3stside what are your plans for this PR?

**Comment by W3stside** [comment]
the css changes I'll consider re-opening in another PR, closing

**Pull request closed without merging**
