### PR TITLE
Bumping dex-js to update WBTC decimals

### PR DESCRIPTION
**Pull request by alfetopito**
https://github.com/gnosis/dex-js/pull/136

https://github.com/gnosis/dex-js/releases/tag/v0.2.2

https://www.npmjs.com/package/@gnosis.pm/dex-js/v/0.2.2

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr921--dexreact.review.gnosisdev.com

**Comment by josojo** [comment]
Screen Shot 2020-04-15 at 16 36 22
Yes, the prices are correct. But still the orderbook looks strange. No clue what is happening

**Comment by josojo** [comment]
```
[INFO: plot_orderbook_tokenpair.py:196 | <module>()]  === ORDERS (20) ===
[INFO: util.py:419 | log_orders()]  <0x83af1c>  Sell                                  227.272727  [USDC]  for at least                                    0.033424  [WBTC]
[INFO: util.py:419 | log_orders()]  <0xcfe8a7>  Sell                                  227.272727  [USDC]  for at least                                    0.033778  [WBTC]
[INFO: util.py:419 | log_orders()]  <0x64fefc>  Sell                                  227.272727  [USDC]  for at least                                    0.034135  [WBTC]
[INFO: util.py:419 | log_orders()]  <0xa08527>  Sell                                  227.272727  [USDC]  for at least                                    0.034497  [WBTC]
[INFO: util.py:419 | log_orders()]  <0xe7f619>  Sell                                  227.272727  [USDC]  for at least                                    0.034862  [WBTC]
[INFO: util.py:419 | log_orders()]  <0x3a468d>  Sell                                  227.272727  [USDC]  for at least                                    0.035231  [WBTC]
[INFO: util.py:419 | log_orders()]  <0x797acc>  Sell                                  227.272727  [USDC]  for at least                                    0.035604  [WBTC]
[INFO: util.py:419 | log_orders()]  <0x81f156>  Sell                                  227.272727  [USDC]  for at least                                    0.035981  [WBTC]
[INFO: util.py:419 | log_orders()]  <0xe4a386>  Sell                                  227.272727  [USDC]  for at least                                    0.036362  [WBTC]
[INFO: util.py:419 | log_orders()]  <0xf20d27>  Sell                                  227.272727  [USDC]  for at least                                    0.036747  [WBTC]
[INFO: util.py:419 | log_orders()]  <0x105fa0>  Sell                                  227.272727  [USDC]  for at least                                    0.037136  [WBTC]
[INFO: util.py:419 | log_orders()]  <0x04699f>  Sell                                    0.040587  [WBTC]  for at least                                  281.854234  [USDC]
[INFO: util.py:419 | log_orders()]  <0x98f55c>  Sell                                    0.040587  [WBTC]  for at least                                  284.838517  [USDC]
[INFO: util.py:419 | log_orders()]  <0x4ac143>  Sell                                    0.040587  [WBTC]  for at least                                  287.854397  [USDC]
[INFO: util.py:419 | log_orders()]  <0x365911>  Sell                                    0.040587  [WBTC]  for at least                                  290.902210  [USDC]
[INFO: util.py:419 | log_orders()]  <0xb93bf9>  Sell                                    0.040587  [WBTC]  for at least                                  293.982293  [USDC]
[INFO: util.py:419 | log_orders()]  <0xb0c6fe>  Sell                                    0.040587  [WBTC]  for at least                                  297.094988  [USDC]
[INFO: util.py:419 | log_orders()]  <0xe6ad3d>  Sell                                    0.040587  [WBTC]  for at least                                  300.240640  [USDC]
[INFO: util.py:419 | log_orders()]  <0x483f08>  Sell                                    0.040587  [WBTC]  for at least                                  303.419599  [USDC]
[INFO: util.py:419 | log_orders()]  <0xfed275>  Sell                                    0.040587  [WBTC]  for at least                                  306.632216  [USDC]

```
This is the data on the direct trades. There is no huge order buying WBTC for this tiny price.

@fleupold Maybe you can help with the reason for this strange data point.

**Comment by alfetopito** [comment]
> Screen Shot 2020-04-15 at 16 36 22
> Yes, the prices are correct. But still the orderbook looks strange. No clue what is happening

As mentioned on Slack, the orderbook values are completely transparent to the UI.
Meaning, fixing the API will fix the frontend as well.

**Comment by fleupold** [comment]
I believe the 18k outlier is someone willing to buy WBTC for a ridiculously low price (less than 1$ for 1 BTC). It might be confusing that the x axis is not linearly spaced.

**Pull request merged**
