### PR TITLE
Release/0.10

### PR DESCRIPTION
**Pull request by anxolin**
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2F26vUDLOP9YIc8oxGg%2Fgiphy.gif&token=rocket" data-gitmeme-token="rocket"></a>

Preparing release `v0.10`

Let's freeze develop right now, only cherry pick the price suggestion PR when is ready. Tests can start already.

# Changes

`git log master..release/0.10 --oneline --decorate=0`

eeba2a1 Restore commits (#737)
6c348e5 tabIndex order in <a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2F5C2og3MUmuFanmvYnW%2Fgiphy.gif&token=trade" data-gitmeme-token="trade"></a> (#732)
b697950 change widget size on/connect-wallet (#728)
83d99a7 FAQ and text changes (#730)
9fe8652 Yet another fix for token selector (#727)
fe3fc01 Merge pull request #724 from gnosis/remove_datatype
23b20ad 691/use max locale (#721)
4f3fb73 Fixing filled amount for pending orders (#722)
2deb055 remove datatype
3b28d81 style based on readonly attribute
c2ed8da Merge pull request #720 from gnosis/connect_wallet_action
70571f6 fix lint:fix script
4515915 add link
18078cb style on hover
fda7788 allow to connect by clicking wallet img
43f65b4 696/trade page formatting (#711)
b7af0d2 Pooling interface rework (#683)
47f1130 Merge pull request #715 from gnosis/md_FAQ
8acc555 Merge pull request #689 from gnosis/onChain_analytics
09e560e OnChain analytics screen size (#703)
64b1a3b Add links to devportal in liquidity page (#709)
02ba72b use attribute plugin for markdown links
a994245 rename Component
0000d8a Rotate OrdersPage chevron on click (#713)
9300759 fix names
697fbef add link to <a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2FQ5Fn7viATGFYeW2D2X%2Fgiphy-downsized-medium.gif&token=faq" data-gitmeme-token="faq"></a>
f7fb9ec add <a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2FQ5Fn7viATGFYeW2D2X%2Fgiphy-downsized-medium.gif&token=faq" data-gitmeme-token="faq"></a> route
4078ddc add FAQ page
f8c41d4 add FAQ.md asset
26fa2d5 add markdown loader
709bcff add MIN_GAS_PRICE substitution when possible to fit flags
2ce407d more renames
1b95cb4 smaller flagWithMaps destructure
0ef72b4 add comments
4ac1491 rename stuff
3b01090 Fix trade errors (#712)
6f4eb6e Added custom react-select component for new styling (#626)
13ab93f 500/Fix NaN prices on orders page (#706)
18a46b7 694/make buttons more disably (#704)
baf9887 Feature/misc style fixes (#656)
a22b3fa change styles not to use 100vh (#705)
10641c2 fix comment
db65e74 update userPrint on screenSize change
6c97936 add screenSize to userPrint
f67025e add screenSize flags
56c4c95 add media query detection
a60e29d Updating dex-js to add Chai
ac469f8 Misc changes (#698)
2b20248 Bump typescript from 3.7.5 to 3.8.3 (#669)
a5200ab remove log
09572f7 fix typo
ce9c0d1 add detect-browser dependency
826638f fix WalletApiMock types
54f2247 add userPrint generation to WalletApi
7884f65 add our specific encoder/decoder
fc226ed export utils/flagCodes
b84097d add tests for earmmarking function
2f19d32 add earmarking function
8cd7903 add decoder tests
8d0758d add encoder tests
47157b5 add decoder
6a0a57b add encoder
e483d60 add tentative flags
ea238da Refactoring pending and regular orders classification on orders page
15ea5b8 Bump eslint-plugin-react from 7.18.0 to 7.18.3
44ed383 Bump @types/enzyme-adapter-react-16 from 1.0.5 to 1.0.6
ab8bec3 Bump @gnosis.pm/dex-js from 0.1.12-RC.0 to 0.1.12
fb942e5 Bump react-dev-utils from 10.0.0 to 10.2.0
3d41cc9 Merge branch 'master' into merge-hotfix-v0.9.1
0f00636 autofocus deposit field (#682)
1a2ca11 Non-blocking Deposit/Withdraw modals (#677)
d7b0d42 Display balance on trade page token selector (#599)
67f578c 0.9.0 master merged into develop (#671)
86b8cd5 Visible button fix (#663)
31e0044 Typo fix: bach -> batch
030e606 Bump fork-ts-checker-webpack-plugin from 4.0.3 to 4.0.4
b830f7b Triggering wallet connection from trade page on submission (#598)
2bcf45a hack for modali screen flash (#650)
8c1ec27 Render optimization (#647)
61f4c1b Do not disable the send button (#642)
c725805 Close form on Escape (#637)
eb336a5 527/set order start time (#608)
25a3dbf Fix price issue (#631)
09f4ae6 Delete unused column (#641)
1d1a5c7 Autofocus sell input (#638)
4ea8542 Overall layout updates. (#635)
2f6d6e5 Bump @walletconnect/web3-provider from 1.0.0-beta.46 to 1.0.0-beta.47
b4980d9 Bump @types/jest from 25.1.1 to 25.1.3
2692ece Fix balance always on error state (#632)
2ebc209 Hide todo (#624)
3fd9473 Misc style updates. (#607)
737b5b9 fix button.type
50eb8e1 Hide functionalities not included in ethcc version (#617)
17d6cfb Hide deposit and enable for receive token (#609)
4df3344 Improved connect wallet in orderspanel. (#614)
1123dfb Fix form submission (#616)
4bbe470 Feature/toast and fonts design (#601)
4823813 Merge branch 'master' into develop
2fdf9a7 correct deps for readOnly register inputRef (#605)
54a617c 481/add price (#551)
8617685 Improve tokenSelector styles. (#597)
9f9634d Improve logs (#576)
1592733 Balances overview styles update. (#586)
4393f61 528/show from date on orders (#584)
30ae106 Fixing orders not loading on landing page first load
2c2e6b7 588/wallet not connected orders page (#590)
f515e2c Bump eslint-plugin-jest from 23.6.0 to 23.8.0
cd8df63 Feature/orders panel design (#582)
f8e4bc3 Added favicon. (#585)
367297b smart disclaimer - persist close (#577)
fa29524 Feature/develop design progress (#565)
b3b2bf4 Child element must be a React component
09e8a2e Remove some debug logs (#573)
6a31aa1 483/liquidity orders tab (#571)
e41a7fb Merge branch 'master' into develop
217dc17 Tooltips sample integration (#566)
9c73258 Added total amount to orders page (#564)
2b60863 Merge branch 'master' into develop
483da77 Addessing pending comments from PR https://github.com/gnosis/dex-react/pull/553#discussion_r380239086
f1ca63f Merge remote-tracking branch 'origin' into develop
3fb4cec Merge redesign onto develop (#553)
05e7e79 Merge remote-tracking branch 'origin/master' into develop
a1c402a Bump @types/enzyme from 3.10.4 to 3.10.5
53c7e21 Bump @types/styled-components from 4.4.2 to 4.4.3
8d7d6a1 Bump @types/node from 13.7.0 to 13.7.1
972c8de Bump @fortawesome/free-solid-svg-icons from 5.12.0 to 5.12.1
9d240f2 Bump @typescript-eslint/parser from 2.18.0 to 2.19.2
b525a45 Fixing bad merge (by me 😅)
b45b839 Refactor format utils and constants (#501)
e0bc970 482/define validity date (#509)
49939d9 477/ notifications displayed longer (#524)
d7ec036 455/global orders (#520)
19f907c select input text on focus (#518)
c29283c Lazy loading + prefetching (#502)
ffbbb30 start with base tag (#522)
50abfbb When a token is not registered in the exchange, do not allow the order to be placed
662eb5c fix variable (#516)
b902aba 478.5/optimistic liquidity (#512)
2c40603 check if new state is needed (#513)
01056db 478/optimistic orders (#498)
bbf658d useOrders v2 (#510)
7ac8826 Bump @fortawesome/free-regular-svg-icons from 5.12.0 to 5.12.1
8b5fcd2 Bump @typescript-eslint/eslint-plugin from 2.18.0 to 2.19.0
bf54dcc Bump rimraf from 3.0.1 to 3.0.2
8c8c328 Bump @types/node from 13.5.2 to 13.7.0
c47828a Bump @fortawesome/fontawesome-svg-core from 1.2.26 to 1.2.27
2dcd92a Bump enzyme-to-json from 3.4.3 to 3.4.4
d490ff6 Bump react-hook-form from 4.7.2 to 4.8.0
ef59150 Bump webpack-dev-server from 3.10.1 to 3.10.2
17ee9de Bump web3 from 1.2.5 to 1.2.6
13b1946 Merge branch 'master' into develop
d95d242 455/paginating orders page (#489)

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr744--dexreact.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr744--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
> fix names
> [697fbef](https://github.com/gnosis/dex-react/commit/697fbefef1df85403bf0e739c37d5332adce83c6) add link to [](https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2FQ5Fn7viATGFYeW2D2X%2Fgiphy-downsized-medium.gif&token=faq)

original gif got 404?

**Comment by Velenir** [comment]
> Travis automatic deployment:
> https://pr744--dexreact.review.gnosisdev.com

@gnosis-info shouldn't doublepost, did something change with travis config?

**Pull request merged**
