### PR TITLE
Testing new contract deployed by Ben for debugging issue #228

### PR DESCRIPTION
**Pull request by alfetopito**
## DO NOT MERGE

Updating contract address to point to @bh2smith deployed contract, which is verified and we can use a web interface to interact with and debug issue we are seeing on #228

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr233--dexreact.review.gnosisdev.com

**Comment by bh2smith** [comment]
Such a Do Not Merge PR would be a lot safer (in terms of preventing merge)  if it were created as a draft.

Screenshot 2019-11-23 at 9 23 26 AM

Such Drafts can not be merged until the "Draft" aspect has been lifted.

**Comment by alfetopito** [comment]
> Such a Do Not Merge PR would be a lot safer (in terms of preventing merge) if it were created as a draft.
> 
> Screenshot 2019-11-23 at 9 23 26 AM
> 
> Such Drafts can not be merged until the "Draft" aspect has been lifted.

Yes, I'm aware.
But I created as a regular PR to have it deployed by our travis bot. I think it doesn't do that for draft PRs.

**Comment by alfetopito** [comment]
We found the issue. Changes here no longer needed.

**Comment by bh2smith** [comment]
> We found the issue. Changes here no longer needed.

Could you please elaborate?

**Comment by alfetopito** [comment]
> > We found the issue. Changes here no longer needed.
> 
> Could you please elaborate?

I meant that the changes in this PR are no longer required. I only pushed them so we could test using your deployed contract.

**Pull request closed without merging**
