### PR TITLE
Show wallet balance and add remove depositing balance

### PR DESCRIPTION
**Pull request by anxolin**
- It consolidates the column `EXCHANGE WALLET` as the balance in the exchange + the depositing amounts
- It removes the `PENDING DEPOSIT` column
- It adds the `WALLET` column

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr60--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
Well, there are still different opinions on the channel. Should we wait for a conclusion before applying this change?

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr60--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
I think the opinions are divided. We can go with this approach for now. It's easy to change

**Pull request merged**
