### PR TITLE
Added batch id to header

### PR DESCRIPTION
**Pull request by alfetopito**
What do you think?

screenshot_2020-06-16_08-58-31

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1110--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
This reminds me of something https://github.com/gnosis/dex-react/issues/932

**Comment by alfetopito** [comment]
> Would it make sense to add a title and show as a title/tooltip the time `From 12:30 to 12:35`?

Seems redundant with the countdown.

> What about showing when it's closed/open for solutions?

Also redundant. The orders have a countdown too.

What I see as good to have is a FAQ entry? Or a tooltip.

**Comment by josojo** [comment]
This is cool. Thanks for doing it so proactively!

I would prefer it if we would see this information of the batch number even when users have opened the orderbook modal. But probably, this would imply bigger design changes, right? It's not critical, just another nice to have.

**Comment by alfetopito** [comment]
> This is cool. Thanks for doing it so proactively!
> 
> I would prefer it if we would see this information of the batch number even when users have opened the orderbook modal. But probably, this would imply bigger design changes, right? It's not critical, just another nice to have.

That would require to either change the modal size so the countdown is always visible or insert the batch time into the orderbook modal, and refresh it at every orderbook update.

Does require a bit more work and thinking besides this 2min fix I did here, hehe. Not THAT much, just a bit more I'm not sure we want to invest right now.

**Pull request merged**
