### PR TITLE
714/selector styling

### LINKED ISSUE #714: Fix token selector styling
Follow up to https://github.com/gnosis/dex-react/pull/626

> @anxolin @W3stside @Velenir should we merge it like this? I'm holding off because of styling.

I vote for merge :) 
We can add an additional issue for styling this. It works, so I'm ok with merging to develop. We just have to review the styles before closing the version

By the way, the GIF you added with the strange behaviour doesn't happen to me. Imo, only a bit of paddings are missing:

image

_Originally posted by @anxolin in https://github.com/gnosis/dex-react/pull/626#issuecomment-598267748_

### PR DESCRIPTION
**Pull request by Velenir**
Closes #714 if everyone likes it

localhost_8080_trade_DAI-USDC_sell=0 price=0 from=0 expires=2880 (1)

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr736--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
> Focus is moved to amount intput.

Nothing to do with this PR. I didn't touch focus, so it's from develop

**Comment by Velenir** [comment]
> Also, can we make the arrows keys to work like in a normal select or select2?

Nothing to do with this PR
Also I don't get what you expect, make an issue.

**Comment by Velenir** [comment]
> Can we make the text smaller

Done

**Comment by anxolin** [comment]
Ok. I'll make an issue for the arrow keys thing. Agree is not part of this PR.

Also another "nitpick", why do we have what it looks like 3-4 different size close window icons?

Big:
image


image

image

image



Maybe for the last one is fine to be smaller. But all the others should share the same styles

**Comment by alfetopito** [comment]
> > Focus is moved to amount intput.
> 
> Nothing to do with this PR. I didn't touch focus, so it's from develop
> Also this doesn't happen locally for some reason

What the hell, works for me in local as well :|

**Comment by Velenir** [comment]
> I just tested and this does not happen on `develop`.

It does happen on dex.dev.gnosis...
And the worst part it only happens in production, try `yarn build && serve -d ./dist`

**Comment by Velenir** [comment]
> But all the others should share the same styles

Done

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr736--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
> Travis automatic deployment:
> https://pr736--dexreact.review.gnosisdev.com

Didn't we have a check so that gnosis-info bot won't post twice?

**Comment by W3stside** [comment]
@Velenir can you change the scroll bar css to match the main app?

**Comment by Velenir** [comment]
> can you change the scroll bar css to match the main app

Don't think that's a good idea. We never styled scrollbars, so they are what browser decides they are.
We either style globally for every overflown element or we don't
Whoever wants to have a go at it, help yourself to [this nice resource](https://css-tricks.com/the-current-state-of-styling-scrollbars/#article-header-id-0)

**Pull request merged**
