### PR TITLE
Walletconnect update X

### PR DESCRIPTION
**Pull request by Velenir**
Multiple hacks to allow to use latest `@walletconnect/web3-provider`

### CODE REVIEW

**Comment by Velenir** [comment]
I don't know why Travis isn't running here. Any ideas? This is not the first time thet Travis doesn't run in a PR to a PR (not to `develop`)
Would be cool if you checked out locally

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1085--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
And now it runs, hm

**Comment by Velenir** [comment]
Can you try locally?

**Comment by alfetopito** [comment]
> Can you try locally?

Same overall result, although slightly different.

Still no orders nor balances.

Now I don't see the wallet component on top:
screenshot_2020-06-04_09-43-43

And it seems like requests are being made (I turned on debugging before but don't recall having any calls logged)
screenshot_2020-06-04_09-44-59

**Pull request merged**
