### PR TITLE
Fix Firefox placeholder

### LINKED ISSUE #679: Input placeholder has weird placements
Screenshot from 2020-03-03 16-06-52

Once a value is inserted, value is properly aligned.

### PR DESCRIPTION
**Pull request by Velenir**
Closes #679 

Seems to work, but is hacky.
Also seems not to break or other browsers but who knows.

Please someone check in Safari and co.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr681--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
Errr, not quite...

Screenshot from 2020-03-04 09-55-08

**Comment by Velenir** [comment]
That's your Firefox that's wrong :angry: 

@biocom can you weigh in, what can we do here?

**Comment by biocom** [comment]
Tried several approaches (line-height: inherit and line-height: normal) on the ::placeholder element. But only this one seemed to work:
Screenshot 2020-03-04 at 15 00 36

**Comment by biocom** [comment]
Seems to do no harm on Chrome:
Screenshot 2020-03-04 at 15 06 43

**Comment by W3stside** [comment]
~`placeholder`~ ... we dont need it

**Comment by biocom** [comment]
> ~`placeholder`~ ... we dont need it

Yes, you can also just add it to the `input` element itself. Weird issue, as the trade form doesn't need this.

**Comment by Velenir** [comment]
Closing as the placeholder will be no more

**Pull request closed without merging**
