### PR TITLE
minimal banner

### LINKED ISSUE #185: Minimalistic disclaimer for raw interface
The web should not contain any specific info in the disclaimer.

Remove disclaimer and add a minimalistic message similar to other webs like uniswap:

image

TODO: Confirm the specific message

### PR DESCRIPTION
**Pull request by W3stside**
closes #185

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr230--dexreact.review.gnosisdev.com

**Comment by W3stside** [comment]
> Looking good!
> 
> Only one question, and I know is not related to these changes, and I've seen this for a long time, but I'll raise it here anyway.
> 
> When in full screen, the banner is huuuge:
> 
> big-banner
> 
> Intentional?

huge banners are life - but not not really intentional, let me look at it. tho who uses a screen that big???

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr230--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
> huge banners are life - but not not really intentional, let me look at it. tho who uses a screen that big???

Nice!!! Double approve!

**Comment by Velenir** [comment]
> huge banners are life

minimal banner, maximal swag

**Pull request merged**
