### PR TITLE
widen orderswidget in trade page

### LINKED ISSUE #1113: Widen Trades page OrdersWidget
Set to `50vw` for example

### PR DESCRIPTION
**Pull request by W3stside**
Closes #1113 

Screenshot from 2020-06-17 16-40-13

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1115--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
is this Firefox being finicky?
screenshot_2020-06-17_10-14-03

**Comment by W3stside** [comment]
> is this Firefox being finicky?
> screenshot_2020-06-17_10-14-03

whoa that's ugly, haha. let me try with FF

**Comment by W3stside** [comment]
@alfetopito how is it now?

**Pull request merged**
