### PR TITLE
easier logout process

### PR DESCRIPTION
**Pull request by W3stside**
Light mobile:
Screenshot from 2020-08-24 11-36-32

Light web:
Screenshot from 2020-08-24 11-36-40

Dark mobile:
Screenshot from 2020-08-24 11-38-21

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1341--dexreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]
Veeery beautiful :sparkles: 

But dark-on-dark QR can be a problem. For one, my phone can't read it. Consider adding white `padding|border|outline|box-shadow`

**Review by anxolin — COMMENTED** [review]
Thanks for this! Makes thing better.

What do you think about leaving only one button (make the etherscan thing just a link):

image

Also, I wouldn't use the magnifying glass icon, since this is associated with search. Could u use the same Metamask uses? 
image

Please, take in consideration Dima's comment in darkmode, we had issues before.
Probably works if you add the qr in a small white box with just a super small padding.

**Comment by anxolin** [comment]
Also, consider moving the icon up, and make it a bit wider and with slightly more padding
the reasoning is:
- if it's wider and with more padding, is more prominent and easy to click, but most importantly it doesn't create one strange effect when it resizes while it shows "logging out" message
- Moving up is because the toast messages cover the button in responsive mode. See image:

IMG_6582

IMG_6583

**Comment by W3stside** [comment]
@Velenir @anxolin I prefer the link as a button, but I'll leave it as a vote

button: :stop_button: 
link: :link:

**Comment by W3stside** [comment]
which u cant do directly on the comment cause GH is dumb

Vote: :stop_button:

**Comment by alfetopito** [comment]
link

**Comment by W3stside** [comment]
> link

Excuuuuse me did I ask you? :tipping_hand_woman:

**Comment by alfetopito** [comment]
> > link
> 
> Excuuuuse me did I ask you? tipping_hand_woman

Too late now, public page :shrug:

**Comment by anxolin** [comment]
link, with same icon as MM :P

**Review by anxolin — CHANGES_REQUESTED** [review]
still not address issues, like move the to the top, and make the etherscan link a link. It doesn't need so much protagonism

**Comment by W3stside** [comment]
> still not address issues, like move the to the top, and make the etherscan link a link. It doesn't need so much protagonism

didn't understand the `move the icon to the top` part, top of the toast notification? which I did, or move the whole wallet card to the top of the screen? Guessing the latter is what u meant now. For the link i was checking as I wanted to see what others wanted, can't always make what you suggest without asking! I prefer the button

**Comment by anxolin** [comment]
> move the icon to the top part, top of the toast notification

I was just flagging that when you have any toast, the button is not clickable, and maybe moving it to a upper position would solve the issue.
image

> For the link i was checking as I wanted to see what others wanted, can't always make what you suggest without asking! I prefer the button

I didn't mean you blindly do what I suggest. I try to encourage just the opposite. If you feel strongly about anything, you should try to make your points in public channels. I think you asking was a good thing. Why I said that "still not addressed issues" was because I was asked to review again, but this issue was not resolved (you asked, and for now people prefer link). I would expect that we reach a decision, and we send the request again, otherwise I'm reviewing the changes I disagreed in the first place. 

Having said that, I don't care that much about button or link. My argument is, the main action there is to sign out, the link is just a "satellite" functionality that doesn't need so much attention. I don't care too much what we decide in this matter. Ask maybe Michel and he can decide :)

**Comment by Velenir** [comment]
My preference
pr1341--dexreact review gnosisdev com_trade_DAI-USDC_sell=0 price=0 from= expires=

**Comment by W3stside** [comment]
@anxolin moved the entire wallet up, maybe that's better, check it now pls

**Review by anxolin — APPROVED** [review]
> @anxolin moved the entire wallet up, maybe that's better, check it now pls

Actually, I just meant the button, and not the whole wallet pop up, but I'm glad you understand it like this, I like your suggestion more.


Some small detail in responsive, the copy icon shows in the next line. Also, I think I should be able to click in the address and icon, not just in the icon. Remember the fat finger (like me) people are people too 
image

**Comment by biocom** [comment]
Just to add my comment: I like that last screenshot shared by Anxo. In my view 'Logout' might be more of a primary action than 'View on Etherscan'. Making 'Logout' the single button therefore I think makes the most sense. Also for comparison this is what Uniswap uses:

Screenshot 2020-08-26 at 13 25 17

**Comment by anxolin** [comment]
> Just to add my comment: I like that last screenshot shared by Anxo. In my view 'Logout' might be more of a primary action than 'View on Etherscan'. Making 'Logout' the single button therefore I think makes the most sense. Also for comparison this is what Uniswap uses:

I like that they call disconnect, it would make it more coherent. Note we call it connect VVVVV
image



Just regarding the Etherscan link, I think should be a link link, I see it was kept as a "secondary button" that looks like a link until you hover on it. It looks better, but I don't see a big reason to make it stand out so much. hehe, I leave it up to u guys 😅

**Pull request merged**
