### PR TITLE
Parallel verify script

### PR DESCRIPTION
**Pull request by Velenir**
Run `linters` and `test` in parallel, cuts down on `pre-commit` hook time a bit. Actual time would depend on your cpu, of course, mine:

```sh
# sequentially
# to run old scripts in this branch
# time ( npm run lint:js && npm run lint:css )
> time npm run lint
real	0m16,258s
user	0m23,423s
sys	0m2,360s

# in parallel
> time npx npm-run-all --parallel lint:*
real	0m12,145s # -4s
user	0m23,783s
sys	0m2,253s


# sequentially
# to run old scripts in this branch
# time ( npm run lint:js && npm run lint:css && npm run test )
> time npm run verify
real	0m22,875s
user	1m4,082s
sys	0m5,508s

# in parallel
> time npx npm-run-all --parallel lint:* test
real	0m16,795s # -6s
user	1m11,440s
sys	0m5,829s
```

`real` time is the most important
If your timings are significantly different, please post them.

### CODE REVIEW

**Comment by W3stside** [comment]
is that safe tho running the linters in parallel? there isn't a possibility of clashing as it's css in js linting? guess we'll see

**Comment by Velenir** [comment]
> is that safe tho running the linters in parallel? there isn't a possibility of clashing as it's css in js linting? guess we'll see

As long as they are read-only, shouldn't be a problem. Now if we ran with `--fix`, I'd expect problems.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1490--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1490--dexreact.review.gnosisdev.com/storybook/)**: Component stories

**Comment by alfetopito** [comment]
# 1
```bash
$ time ( npm run lint:js && npm run lint:css )
41.37s user 1.87s system 164% cpu 26.305 total
```

# 2
```bash
$ time npx npm-run-all --parallel 'lint:*'
43.77s user 1.87s system 227% cpu 20.076 total
```

# 3
```bash
$ time ( npm run lint:js && npm run lint:css && npm run test; )
298.24s user 9.31s system 424% cpu 1:12.50 total
```

# 4
```bash
$ time npx npm-run-all --parallel 'lint:*' test
120.95s user 6.88s system 464% cpu 27.493 total
```

**Comment by Velenir** [comment]
@alfetopito
That's quite an improvement for the last one :scream:

**Comment by alfetopito** [comment]
> @alfetopito
> That's quite an improvement for the last one scream

Hell yeah.
That's why I stopped running pre-commit hooks =P
Ain't got not time to wait all this to run for every single commit!

**Comment by alfetopito** [comment]
And also, damn! How can you run all that 10x faster than me? Is my computer that crappy, from 15 years ago or something ? o.O

**Comment by Velenir** [comment]
> And also, damn! How can you run all that 10x faster than me? Is my computer that crappy, from 15 years ago or something ? o.O

It's a good idea to run the scripts a few time before timing, to warm the cache, etc.Then you'll get more average results.

**Review by W3stside — APPROVED** [review]
nice

**Review by anxolin — COMMENTED** [review]
`1.`
npm run lint  
23.24s user 
2.90s system 
205% cpu 
12.716 total

`2.`
npx npm-run-all --parallel "lint:*"  
23.18s user 
2.96s system 
205% cpu 
12.749 total

`3.`
npm run verify  
104.31s user 
21.54s system 
707% cpu 
17.777 total

`4.`
npx npm-run-all --parallel "lint:*" test  
100.77s user 
21.12s system 
719% cpu 
16.933 total

**Comment by anxolin** [comment]
It's weird in my case, not only i don't get a big difference, but I sometimes get worse times using `npm-run-all`

**Comment by Velenir** [comment]
> It's weird in my case, not only i don't get a big difference, but I sometimes get worse times using `npm-run-all`

Did you run like this `time npm run lint` or like this `time ( npm run lint:js && npm run lint:css )`

**Comment by W3stside** [comment]
Sequential:

```bash
real	0m12.105s
user	0m18.544s
sys	0m0.925s
```

Parallel
```bash
real	0m9.048s
user	0m19.039s
sys	0m1.044s
```

**Comment by anxolin** [comment]
@Velenir 

> Did you run like this time npm run lint or like this time ( npm run lint:js && npm run lint:css )
Now I ran it as u intended


Sequencial:
`88.00s user 19.30s system 492% cpu 21.771 total`

Parallel:
`95.77s user 19.81s system 779% cpu 14.830 total`

**Comment by Velenir** [comment]
> Sequencial:
> `88.00s user 19.30s system 492% cpu 21.771 total`
> 
> Parallel:
> `95.77s user 19.81s system 779% cpu 14.830 total`

See how cpu rose -- means all your cores had more work to do, as a result -5 sec
So, can I get an approval?

**Review by anxolin — APPROVED** [review]
If u ask this nicely, sure!
Thanks Dima

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
