### PR TITLE
Feature/misc style fixes

### PR DESCRIPTION
**Pull request by biocom**
Optimise wrapping and general styling of the form error:
Screenshot 2020-02-28 at 14 41 45
Screenshot 2020-02-28 at 14 41 34
Screenshot 2020-02-28 at 14 30 02

Validity modal styling + add title and X (close) button for modal.
Screenshot 2020-02-28 at 14 33 54

Please check the onclick event for the X closing modal. Right now it does the exact same thing as clicking on the main blue button. So it seems to save the value also on close X. Might be good or not.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr656--dexreact.review.gnosisdev.com

**Comment by W3stside** [comment]
I think it's fine as is

**Comment by W3stside** [comment]
@Velenir @alfetopito @anxolin why has this not been merged yet? are we waiting on sth?

**Comment by alfetopito** [comment]
> @Velenir @alfetopito @anxolin why has this not been merged yet? are we waiting on sth?

Probably waiting for someone to merge it :D

**Pull request merged**
