### PR TITLE
better CSS add token from selector

### LINKED ISSUE #884: Review design and messages of add token
Improve styling and messages for:

Loading:
image

Confirmation:
image

Mobile:
IMG_24BD59481F4D-1

IMG_C0A06C2D1724-1

### PR DESCRIPTION
**Pull request by W3stside**
closes #884 i hope

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1090--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
Well, since we are at it, can I make a request? Give some love to the add token button as well.
Doesn't match the style we have for other buttons:

screenshot_2020-06-08_15-07-50
screenshot_2020-06-08_15-07-36

**Comment by W3stside** [comment]
Screenshot from 2020-06-09 12-04-59

Fixed button css

**Comment by W3stside** [comment]
Screenshot from 2020-06-09 12-05-57
Fixed button css

**Comment by Velenir** [comment]
[when adding 2 tokens](https://pr1090--dexreact.review.gnosisdev.com/trade/0x1fc31488f28ac846588ffa201cde0669168471bd-0x98CC3BD6Af1880fcfDa17ac477B2F612980e5e33?sell=0&price=0.99700&from=&expires=2880)
2tokens
Would it look better with token images aligned vertically? And then `Check on etherscan` aligned right

**Comment by W3stside** [comment]
Update

Screenshot from 2020-06-15 09-41-12

**Pull request merged**
