### PR TITLE
Develop into a future release/v.1.6.0?

### PR DESCRIPTION
**Pull request by Velenir**
- Add best ask API (#1477)
- useForm / react-hook-form storybook decorator (#1482)
- add check-types script (#1515)

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1522--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1522--dexreact.review.gnosisdev.com/storybook/)**: Component stories

**Comment by W3stside** [comment]
but all these changes we want for 1.6 no?

**Comment by Velenir** [comment]
I just wanted to bring release (and master) up to speed with develop.
Can't these changes to into 1.5?

**Comment by Velenir** [comment]
Will be recreated for future release anyway

**Pull request closed without merging**
