### PR TITLE
gasPrice and tx.data middlewares

### PR DESCRIPTION
**Pull request by Velenir**
Moves gasPrice and earmarking logic into provider middlewares
For earmarking uses existing encoder, but now we can use not only numbers but hex values. Which presents a good opportunity to change `SENTINEL` to something interesting
For example, `feed` or `dad` or even `feeddad`

Works for me, bu I would appreciate some extra testing for all transactions we have in UI :pleading_face:

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1013--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
@alfetopito does it freeze on develop too?

**Comment by Velenir** [comment]
> * Trade
> * Liquidity
> * Enable
> * Deposit
> * Withdraw
> * Claim
> * Cancel
> * Delete

Tested with Gnosis Safe. Works!

**Comment by Velenir** [comment]
> on MM the page freezes

Couldn't reproduce no matter what I tried
@anxolin , @W3stside can you try?

**Comment by alfetopito** [comment]
> @alfetopito does it freeze on develop too?

Yes it does...

At least on FF 
screenshot_2020-05-19_10-04-10

But only when switching from Rinkeby to Mainnet, not the other way around ... :/

Had no issues whatsoever on Chrome... :(

**Pull request merged**
