### PR TITLE
Fix price format in orders

### LINKED ISSUE #1129: Order price not shown correctly
For this account 0x2e173510024d480d195d8875e4d55e9b6198b654,
I have the following order
Screen Shot 2020-06-20 at 08 59 08

the inverse price of 0.1 is 1? Hmm...

### PR DESCRIPTION
**Pull request by Velenir**
Fixes #1129 
Depends on gnosis/dex-js#155

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1141--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
Dima, is this sth that should go in the hotfix?

**Comment by Velenir** [comment]
> Dima, is this sth that should go in the hotfix?

Not high severity, doesn't have to go in hotfix, can be in next release.
<sub><sub>I just don't want to recreate this PR form master to hotfix/

**Comment by W3stside** [comment]
> Dima, is this sth that should go in the hotfix?

I think sth that affects number this heavily should go into it, no? `0.99999` being represented as `0.1000` is a majour bug imo, @alfetopito @anxolin @Velenir

**Comment by anxolin** [comment]
> I think sth that affects number this heavily should go into it, no? 0.99999 being represented as 0.1000 is a major bug imo, @alfetopito @anxolin @Velenir

Let's make sure our dev version reaches production soon. We addressed already the most pressing issues for hotfix. Let's try to wrap up a version asap

**Pull request merged**
