### PR TITLE
Add token through NoOptionsMessage

### PR DESCRIPTION
**Pull request by Velenir**
ezgif-4-07b765fb5a16

Do you like it? I like it very much now. 
<sub><sub><sub><sub><sub><sub>I'll make you like it :smiling_imp: </sub>

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr839--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
Heheh, I had to look at your description, didn't know how you added that markup :) 
now I know

image

**Comment by Velenir** [comment]
> A link to the devoportal (https://docs.gnosis.io/protocol/docs/addtoken1) here

Should it be https://docs.gnosis.io/protocol/docs/addtoken5/ instead?

**Comment by anxolin** [comment]
Good point, although I think that is better the step 1, cause maybe the user doesn't have OWL

**Comment by Velenir** [comment]
> I've just test it functionally, cause there's a many changes now (since it's showing all the changes from previous PRs as well)

Oh heck, it's cause I needed changes from ExchangeApi that @alfetopito made, so I merged develop.

**Pull request merged**
