### PR TITLE
Update dex-js to v0.2

### PR DESCRIPTION
**Pull request by anxolin**
Just that, update dex-js to v0.2 😊

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr865--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
Hmmm, I don't think we do that in a PR, because the tag is on the branch.
Instead we do the version tagging directly on `master` after merging in `develop`, no?

I thought this was the process, at least this is how I released the last few versions.

**Comment by anxolin** [comment]
Yes, but here I'm updating in the web the dex-js. I'm doing dependabot's job here :)

**Comment by alfetopito** [comment]
> Yes, but here I'm updating in the web the dex-js. I'm doing dependabot's job here :)

:facepalm: 

Pretend I didn't say anything...

**Pull request merged**
