### PR TITLE
655/eternal darkness

### LINKED ISSUE #655: remove dark-mode but re-enable for later version
Check TODO comments inside `ThemeToggler`

### PR DESCRIPTION
**Pull request by W3stside**
Closes #655 

# RE-ADD THE DARKNESS

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr792--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
Great work, only couple places missed

pr792--dexreact review gnosisdev com_trade_DAI-USDC_sell=0 price=1 03195 from=0 expires=2880

numbers not very readable
pr792--dexreact review gnosisdev com_trade_DAI-USDC_sell=0 price=1 03195 from=0 expires=2880 (1)

do we want to style help tooltips a darker color? I vote no
pr792--dexreact review gnosisdev com_trade_DAI-USDC_sell=0 price=1 03195 from=0 expires=2880 (3)

Also, do we want to style WalletConnect modal?

**Comment by W3stside** [comment]
Thanks @Velenir will change it

**Comment by alfetopito** [comment]
Minor issue.

Too dark maybe?

screenshot_2020-03-31_09-33-07_144506434

Hard to see the `balance`, the switcher arrows and similar colored text

**Comment by anxolin** [comment]
Should we merge, probably we can close #798 with this one

**Comment by anxolin** [comment]
Confirmed, it closes #798

**Comment by W3stside** [comment]
would love 1 final check through! @anxolin @Velenir @alfetopito

**Comment by alfetopito** [comment]
> Confirmed, it closes #798

Partially.

The label is not fixed on FF
screenshot_2020-04-03_09-40-17

Otherwise, looks good :+1:

**Comment by anxolin** [comment]
image

I would just review the color of the text of the input. It's not very readable

Maybe even this RED is to hard for me:
image

A bit softer maybe is easier on the eyes?
image

**Pull request merged**
