### PR TITLE
Network check 2

### LINKED ISSUE #283: The app breaks when you are not in the right network
We should inform the user that network is not supported

### PR DESCRIPTION
**Pull request by W3stside**
#1543 was broken somehow in backend so retrying here...

Closes #283

Deals with incorrect network using CONFIG list's default accepted networks and uses toast.error pointing users to a our repo's wiki about networks.

THE URL IN THE TOAST ERROR NEEDS TO POINT ELSEWHERE!! Right now it is pointing to THIS repo.

Thoughts on toast approach?

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1546--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1546--dexreact.review.gnosisdev.com/storybook/)**: Component stories

**Review by Velenir — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
Cool! I like it!

Only comment, can you try setting `closeButton: false` and `closeOnClick: false`

**Comment by W3stside** [comment]
@anxolin @Velenir thoughts on the URL in the toast pointing to this repo's wiki?

**Comment by anxolin** [comment]
I think is good! 👌

**Review by anxolin — APPROVED** [review]
Works great

**Comment by Velenir** [comment]
> @anxolin @Velenir thoughts on the URL in the toast pointing to this repo's wiki?

Good thoughts :+1:

**Pull request merged**
