### PR TITLE
Pooling interface back button rework

### PR DESCRIPTION
**Pull request by W3stside**
There were some remaining issues with back button addressed here:

1. disappearing back button when it shouldn't have been
2. formatting
3. not disabled when it should have been

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr710--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
> There were some remaining issues with back button addressed here
Can you develop a bit the description?

**Comment by anxolin** [comment]
The positioning of the button looks off. I see now it's disabled when you send the transaction. I think it's fine, although maybe better to hide it, also would solve the positioning thing too :) 

image

**Comment by Velenir** [comment]
I don't see that wrong `< BACK` positioning

**Comment by W3stside** [comment]
Positioning was fixed in last commit

**Pull request merged**
