### PR TITLE
Footer edit

### LINKED ISSUE #1323: Powered by Gnosis Protocol message
:steam_locomotive:`Powered by Gnosis Protocol`   message somewhere in the footer

### PR DESCRIPTION
**Pull request by W3stside**
Hopefully closes #1323

Reworks footer with Powered By Gnosis Protocol badge

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1326--dexreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]
Maybe a bit more `line-height` on `.innerWrapper`

pr1326--dexreact review gnosisdev com_trade_DAI-USDC__sell=0 price=0 from= expires=

**Review by anxolin — COMMENTED** [review]
I still thing is not right:
The FAQ is important, and it has less protagonism than the theme.

Also, the layout is a bit strange, and the text is too tight.
image


I vote for:
image

**Comment by alfetopito** [comment]
Comment from someone with no design knowledge: 
- The badge color doesn't match anything in the page
- The badge size looks too large for this sort of badge

Feels weird

**Comment by anxolin** [comment]
> Comment from someone with no design knowledge:
>
>The badge color doesn't match anything in the page
>The badge size looks too large for this sort of badge
>Feels weird

The logo color is the one of the protocol, we can't change. Ofcouse we can change the web, but this PR is just to add a "build on top of"
For the size, maybe we can a tiny bit smaller, but it needs to be kind of big to let us read the text in it.

Regarding styles, we validated with Lea this.

Imo, it looks great in desktop! 

For responsive, I think this one is broken:
image

And this one needs more space of separation, the FAQ links are more important. I think they shouldn't be too close to the "theme"
image

**Review by anxolin — COMMENTED** [review]
I need to remember to comment in the review, otherwise it keep showing up as pending for review :)

**Review by anxolin — APPROVED** [review]

**Pull request merged**
