### PR TITLE
Fix WC autoconnect

### PR DESCRIPTION
**Pull request by Velenir**
Removes a long standing hack for the problem of reconnecting when WC was disconnected on wallet-side
May again results in problems in that scenario
But autoconnect is more robust like this.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1157--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
With or without the change I'm seeing issues, albeit different ones.

The control test on https://dex.dev.gnosisdev.com/
- Connect with WC using my safe
- Reload the page: wallet not connected, need to connect again, but without needing to re-scan the qr code. 
- After connecting again: the wallet is connected but I don't see the wallet widget on top
- Disconnect the page from my safe: the app is disconnected immediately
- Reload the page: still disconnected, wallet widget is displayed

This PR https://pr1157--dexreact.review.gnosisdev.com/
- Connect with WC using my safe
- Reload the page: still connected. Wallet widget is displayed, everything it great :+1: 
- Disconnect the page from my safe: nothing changes. 
- Reload the page: still connected, wallet widget is displayed

**Comment by anxolin** [comment]
Why every single sprint we have Wallet Connect issues? 😢

**Comment by Velenir** [comment]
> * Disconnect the page from my safe: nothing changes.
> * Reload the page: still connected, wallet widget is displayed

It works for me, strange
Can you try again, then we can debug more come Monday.

**Comment by alfetopito** [comment]
> > * Disconnect the page from my safe: nothing changes.
> > * Reload the page: still connected, wallet widget is displayed
> 
> It works for me, strange
> Can you try again, then we can debug more come Monday.

Well, today it is working... :shrug: 

Life isn't easy, so I found out something else that doesn't work.
Can't place orders. No error, nothing. Click on the button, enter on the form, has no effect.

Tested on https://dex.dev.gnosisdev.com/ and there the tx shows up in my Safe as expected.

**Comment by Velenir** [comment]
Those issues probably have nothing to do with this issue
This is a small change
Maybe report everything reproducible in separate issues or add to existing ones

**Comment by W3stside** [comment]
@Velenir hmm seems fine to me, accepting

**Pull request merged**
