### PR TITLE
Confirmmodal for txes

### PR DESCRIPTION
**Pull request by Velenir**
localhost_8080_trade_USDT-DAI_sell=2 price=0 96764 from= expires=2880

Style me please :pleading_face:

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1252--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
One issue I have with this change is that, validation only triggers after all fields are already valid.

For example, I can hit enter when price/amount fields are empty. 
Nothing happens, but there's no indication of what's wrong.

**Comment by Velenir** [comment]
@alfetopito can you try giving 
```
useForm(validation: 'blur') // or something
```

**Comment by Velenir** [comment]
> I second Leandro comment. I like how in develop, the button to send the form is enabled even with a form with errors. When you send, you get some feedback why is wromg

Rolled back disabled btn

**Comment by anxolin** [comment]
@W3stside can you help with some styling PR?

**Comment by W3stside** [comment]
Please wait for #1310  before merging

**Pull request merged**
