### PR TITLE
Also build storybook on master and develop

### PR DESCRIPTION
**Pull request by Velenir**
<sub><sup><sub>Also build storybook on master and develop</sub></sup></sub>
<sup><sub>Also build storybook on master and develop</sub></sup>
<sub>Also build storybook on master and develop</sub>
## Also build storybook on master and develop
# Also build storybook on master and develop

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1391--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1391--dexreact.review.gnosisdev.com/storybook/)**: Component stories

**Comment by alfetopito** [comment]
What's this for? Not sure I get it.

**Comment by Velenir** [comment]
@alfetopito before storybook was built and deployed for PRs only

**Review by anxolin — APPROVED** [review]
👌

**Review by W3stside — APPROVED** [review]

**Pull request merged**
