### PR TITLE
Refactor default network id logics

### PR DESCRIPTION
**Pull request by anxolin**
Moved to the hook, refactored components

### CODE REVIEW

**Comment by anxolin** [comment]
> I wonder if we depend on networkId === 0 somewhere

I hope not. I modified only the places where we were having the fallback logic

**Comment by anxolin** [comment]
Sorry I didn't mention in the PR, this is changing a bit the behaviour of the Etherscan link on purpose.

Now it shows always a link, so Mainnet by default

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr849--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
> Build is failing, you have some left overs:

Yep, fixed 👍

**Pull request merged**
