### PR TITLE
658/get current prices

### PR DESCRIPTION
**Pull request by alfetopito**
Part of #658 

Implementing contract read method `currentPrices`

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr726--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
> Are we still going forward with this?

Well, not sure we are using it, but adding the method won't hurt (had already coded it before realizing wouldn't be that useful...)

**Comment by anxolin** [comment]
I think this one is not needed, and probably won't ever be. It's a pity it's working and we don't add it, but if we don't need it maybe we should "not merge"?

**Comment by alfetopito** [comment]
> I think this one is not needed, and probably won't ever be. It's a pity it's working and we don't add it, but if we don't need it maybe we should "not merge"?

Agreed

**Pull request closed without merging**
