### PR TITLE
Wallet connect bridge

### PR DESCRIPTION
**Pull request by anxolin**
Adds a new config for wallet connect bridge

Changes also the default to use Gnosis one, since it's more reliable

@nlordell , let me know if this solves your issue

### CODE REVIEW

**Comment by nlordell** [comment]
> @nlordell , let me know if this solves your issue

Unfortunately right now I am no longer seeing any problems on with the normal Wallet Connect bridge.

This one works as well though.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1145--dexreact.review.gnosisdev.com

**Comment by nlordell** [comment]
To clarify my initial statement:
- mesa.eth.link is working 100% of the time now, I no longer need to re-scan multiple times to be able to connect to the app.
- Additionally, mesa.eth.link, all transaction requests are being received by my wallet for signing where as earlier, it was about 80% of transactions requests were received
- This PR also appears to work with my wallet without any issue.

**Comment by nlordell** [comment]
One more comment I forgot to mention: the WC issues did not appear to be unique to Mesa. I also had issues connecting my Safe to Uniswap for example - which also indicates that there was an issue with the WC bridge.

**Pull request merged**
