### PR TITLE
Release/1.3.0

### PR DESCRIPTION
**Pull request by Velenir**
**DON'T SQUASH**

# :notebook: Changes
- **Completely revamps the Advanced Settings** (previously order validity settings) to include custom calendar date picking options, relative starting/ending times, and the ability to select start/end times by batch ID

- **Adds a new column in the order book showing Order ID** and the ability to click **Order ID** and **Market** cells to pre-populate the order filters

- **Show provider name/logo** at the top of the app page in the user's wallet section

- **Introduce a default sell/receive token section inside the current configuration file** to pre-populate the trading page if no tokens passed in URL

- **Footer redesign - adds *Powered by Gnosis Protocol* logo and responsive design changes**

- **Travis build: auto release notes**

- **Show recommended minimum sell amount** to users for clarity on better order experience

- **GP solver subsidize factor** update to better align with current parameters

- **Storybook integration** to facilitate further app development

### :detective: Changelog
cdf11a7 Order validity upgrade (#1269)
e38d570 Allow to change the default initial selection of tokens (#1358)
0ac6ae0 Allow to specify an initial list of tokens in the config (#1357)
fa08458 preliminary Order ID column in OrdersWidget(#1261)
ea4e91e Storybook integration (#1349)
a1ce473 Easier log in/out process (#1341)
f442843 Footer changes: GP logo add, responsive format (#1326)
a72ce62 Subsidize factor change (#1329)
501424c Release notes file for travis builds (#1328)
27e98b3 Use ellipsis and title tag (#1325)
6bab734 Simplify build script
9317341 Recommend min sell amount (#1324)
5e1a671 Provider name in WalletComponent (#1270)

### :bug: Bugfixes/Fixes
16d4cf1 Fix error label for edge-case where selected tokens from URL are the same (#1359)
03b0623 Fix wallet connect/disconnect styling (#1356)
ccae05f Fix Price Suggestions wording (#1346)
995b584 Price Suggestions display and css to better fit responsive/web (#1305)
39d2c19 Fix price validation error on token change (#1340)
f0d0100 Fix HTML validity error (#1338)

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1321--dexreact.review.gnosisdev.com

**Comment by W3stside** [comment]
I'm confused, should we squash this PR? @Velenir @anxolin @alfetopito

**Comment by anxolin** [comment]
> I'm confused, should we squash this PR? @Velenir @anxolin @alfetopito

In case u are not kidding, we squash PRs to this branch, but this PR should not be squashed into master, instead only merged
Same for merges from master to develop, only normal merges

**Comment by W3stside** [comment]
> > I'm confused, should we squash this PR? @Velenir @anxolin @alfetopito
> 
> In case u are not kidding, we squash PRs to this branch, but this PR should not be squashed into master, instead only merged
> Same for merges from master to develop, only normal merges

hehe was kidding, but thanks

**Comment by anxolin** [comment]
`Issue 1: Customize start/expire don't work if the amount is 0`

1. Go to https://pr1321--dexreact.review.gnosisdev.com/
2. Click in customize: Validation don't allow you to open the modal


`Issue 2: Sometimes it doesn't confirm the order before sending`

1. Go to https://pr1321--dexreact.review.gnosisdev.com/
2. Enter amount to sell: i.e. 100
3. Click price
4. Click customize
5. Close modal using the 🅧 button on the top right corner
6. Send transaction

**Comment by anxolin** [comment]
`Issue 3`: Opens modal for start/expire if you press INTRO key

* Go to https://pr1321--dexreact.review.gnosisdev.com/
* Input a sell amount, i.e. 100
* Press INTRO key

**Comment by anxolin** [comment]
`Issue 4`: Shows "sending transaction" when you are not (in IOS)

* Go to https://pr1321--dexreact.review.gnosisdev.com/
* Input sell amount. i.e. 100
* Click on submit: 
* The confirm modal shows up. Close confirmation modal
* Click on `[+] customize`, change nothing, and close it by selecting "Set order parameters"
* (repeat) Click on `[+] customize`, change nothing, and close it by selecting "Set order parameters"
* Observe how the "Submit Limit Order" button is now with the spinner, and thinks it's sending the transaction

**Pull request merged**
