### PR TITLE
Fix npm audit warnings

### PR DESCRIPTION
**Pull request by alfetopito**
```

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
│               │ istanbul-reports > handlebars                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1164                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dashboard [dev]                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-dashboard > handlebars                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1164                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

found 2 high severity vulnerabilities in 1614641 scanned packages
  run `npm audit fix` to fix 2 of them.

```

Ran `npm audit fix` and `yarn upgrade`

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr127--dexreact.review.gnosisdev.com

**Comment by bh2smith** [comment]
My only question is about yarn and npm (package). I was under the impression that they are both JS package managers and would expect that only one of the two would be necessary at any one time. Is this true? It is common to use both?

**Comment by Velenir** [comment]
Totally redundant to use two package manager.
In the beginning  when the repo was created, me and David used **npm** only. Anxo, I think, uses **yarn** for everything, so it got added at some point.

**Yarn** only setup can interfere with **npm** dependencies handling sometimes, but I've only seen it in projects made with create-react-app. Usually no problems.

We may want to stick to one manager just in case, though

**Comment by alfetopito** [comment]
I second that. We should pick one and stick to it.

In the mean time, I always update both to not have diverging dependencies on different package locks.

**Pull request merged**
