### PR TITLE
Add Storybook link using PRaul

### PR DESCRIPTION
**Pull request by anxolin**
Add the storybook link in travis too

**Review not needed for now: Waiting for travis**

### CODE REVIEW

**Comment by anxolin** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://google.com)**: Testing web app
   * **📚 [Storybook](https://google.com/storybook/)**: Component stories

**Comment by anxolin** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://google.com)**: Testing web app
   * **📚 [Storybook](https://google.com/storybook/)**: Component stories

**Comment by anxolin** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://google.com)**: Testing web app
   * **📚 [Storybook](https://google.com/storybook/)**: Component stories

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1384--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1384--dexreact.review.gnosisdev.com/storybook/)**: Component stories

**Review by W3stside — APPROVED** [review]

**Review by Velenir — APPROVED** [review]

**Pull request merged**
