### PR TITLE
Card component refactor

### PR DESCRIPTION
**Pull request by W3stside**
Cards and style/css refactor

Example can be found in `Card.tsx` - to be deleted after approval

Switches back to more familiar `table` html syntax

Example:

```tsx
// TODO: remove all below
const fakeData = [
  { a: 1, b: 2, c: 3, d: 'Open Drawer' },
  { a: 1, b: 2, c: 3, d: 'Open Drawer' },
  { a: 1, b: 2, c: 3, d: 'Open Drawer' },
]

const webCSS = `
  background: transparent;
  &:not(:first-child) { margin-top: 3rem; }
  > tbody, thead { 
    > tr {
      min-height: 3rem;
    }
  }
`
const responsiveCSS = `
  background: transparent;
  color: #000;
`
export const Test: React.FC = () => {
  const [openDrawer, setOpenDrawer] = useState(false)
  const { innerWidth } = useWindowSizes()

  return (
    <CardTable
      $columns="repeat(4, 1fr)"
      $bgColor="lightgrey"
      $webCSS={webCSS}
      $responsiveCSS={responsiveCSS}
      $rowSeparation="0.7rem"
    >
      <thead>
        <tr>
          <th>One</th>
          <th>Two</th>
          <th>Three</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {fakeData.map((item, index) => (
          <React.Fragment key={index + Math.random()}>
            <tr>
              <td data-label="Yo">{item.a}</td>
              <td data-label="Labels">{item.b}</td>
              <td data-label="Are Dope">{item.c}</td>
              <td data-label="Action">
                <button onClick={(): void => setOpenDrawer(!openDrawer)}>
                  {openDrawer ? 'Close Drawer' : 'Open Drawer'}
                </button>
              </td>
            </tr>
            {openDrawer && (
              <CardDrawer
                responsive={!!innerWidth && innerWidth < RESPONSIVE_SIZES.MOBILE_LARGE_PX}
                closeDrawer={(): void => setOpenDrawer(false)}
              >
                <CardTable
                  $columns="repeat(4, 1fr)"
                  $bgColor="lightblue"
                  $webCSS={webCSS}
                  $responsiveCSS={responsiveCSS}
                  $rowSeparation="0.7rem"
                >
                  <thead>
                    <tr>
                      <th>One</th>
                      <th>Two</th>
                      <th>Three</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {fakeData.map((item, index) => (
                      <React.Fragment key={index + Math.random()}>
                        <tr>
                          <td data-label="Sub 1">{item.a}</td>
                          <td data-label="Sub 2">{item.b}</td>
                          <td data-label="Sub 4">{item.c}</td>
                          <td data-label="Sub 4">Hello World</td>
                        </tr>
                      </React.Fragment>
                    ))}
                  </tbody>
                </CardTable>
              </CardDrawer>
            )}
          </React.Fragment>
        ))}
      </tbody>
    </CardTable>
  )
}
```

image

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr419--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
I's a bit visually jarring how table expands in every direction when opened. Because it's centered vertically
chrome-capture

Would be better something like

chrome-capture (1)

**Comment by W3stside** [comment]
> I's a bit visually jarring how table expands in every direction when opened. Because it's centered vertically
> chrome-capture
> 
> Would be better something like
> 
> chrome-capture (1)

what's the suggested change? happy to implement it!

**Comment by anxolin** [comment]
Cool! I couldn't review all of this code since there's a lot of refactored code, but it looks great.
Happy that you managed to refactor all the cards

**Pull request merged**
