### PR TITLE
Order book: Design review

### PR DESCRIPTION
**Pull request by biocom**

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr859--dexreact.review.gnosisdev.com

**Comment by biocom** [comment]
@anxolin I believe you merged these changes already into your branch(es) correct? Should I then close this pull request and delete this branch?

**Comment by anxolin** [comment]
no no, these changes are not merged. I merged `order-book-btn` to develop, so we need to update this branch and change it to point to develop

**Comment by anxolin** [comment]
@biocom I just tried to merge from develop, but there's conflicts that I think it's better if u solve them, I don't want to break anything

Also, would it be possible to use the whole width in mobile. If I use landscape it don't use it:
IMG_4295

**Comment by anxolin** [comment]
@biocom 

Could you review a bit the style for darkmode too?
image

**Pull request closed without merging**
