### PR TITLE
Proactive bug squashing

### LINKED ISSUE #979: Make Bugs, not Features...
Make new Bugs so we can solve in next sprint
.... 
...
..
.
Bug 'em

### PR DESCRIPTION
**Pull request by Velenir**
ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT ANXO MADE ME DO IT 

try sending any transaction

Closes #979

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr982--dexreact.review.gnosisdev.com

**Comment by Velenir** [comment]
Scan QR for bonus points :wink:

**Comment by alfetopito** [comment]
> Scan QR for bonus points wink

Ok, someone was inspired :rofl:

**Comment by alfetopito** [comment]
> Let's deploy this somewhere! It's amazing for a DEMO

What about in a [fork](https://github.com/gnosis/dex-react/issues/978)? :wink:

**Comment by alfetopito** [comment]
Nooooooooooo, best feature ever!

I think we should keep it and display every time there's a WC error

**Pull request closed without merging**
