### PR TITLE
Fix xDAI token break

### PR DESCRIPTION
**Pull request by Velenir**
When switching to xDAI chain and refreshing the page it would break with `symbol of undefined` error (@anxolin knows what I'm talking about). First experienced at https://pr1449--dexreact.review.gnosisdev.com/

That would happen because we cast TS types for `getToken` to `TokenDetails` when it could be `undefined`
When there are no tokens for the network (in `config.yaml` or elsewhere) `tokens` array becomes empty
So after adding xDAI tokens to config, the error would fix itself, but still not a good idea

This PR allows for `tokens = []` and as a side-effect allows to switch to an unsupported chain without the whole app coming down.
Try Ropsten, for example.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1452--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1452--dexreact.review.gnosisdev.com/storybook/)**: Component stories

**Review by alfetopito — APPROVED** [review]
The app doesn't horribly break anymore when on an unsupported network \o/

**Review by anxolin — APPROVED** [review]
This is great!

I really like the side effect.
We'll probably need to handle the "unknown network logic" higher in the app, and show a nicer message with the list of supported networks. But can be done in a separate PR.

nit: it creates a flickery effect, showing the widget with a couple of tokens, and then disappears. I thought it was on first load only (like, load default network, and then select the actual one), but ir does it every time I change tabs. 
Not a big deal if we address what I mentioned above

**Comment by Velenir** [comment]
> flickery effect

fixed

**Review by anxolin — APPROVED** [review]
>> flickery effect
> fixed

Still happens. Also, is not a big deal

**Comment by Velenir** [comment]
> Still happens. Also, is not a big deal

Build broke, try again

**Review by anxolin — APPROVED** [review]
It works! great fix

**Pull request merged**
