### PR TITLE
Wrap ether: Open modal, basic UI and logic

### PR DESCRIPTION
**Pull request by anxolin**
Part of #789

First PR for the Wrap Ether functionality.
Includes:
* The new button to wrap ether
* The modal
* Some basic validation
* Fill the input of the amount when you click your balance

Doesn't include:
* Getting the actual balance
* Wrapping the ether

## Details

If the selected token is Ether, it'll show a new button:
image

image

The button will open the folling modal:

image

If clicked the link in the available balance, it'll fill the input with all your balance.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr809--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
There's no need to wrap ETH in order to buy WETH, so I think this shouldn't be here.

> image
 


As for the modal, I got that the actual wrapping isn't implemented, so this might just be a side effect of that, but check this:

1. Open modal, nice and easy

screenshot_2020-04-01_08-30-17

Set a value, click continue (maybe a few times)

2. The modal opens again, with a different styling :O

screenshot_2020-04-01_08-30-58


Also, when I click on the amount link, it validates the form and shows the error, so I have to click it twice to fill in the input.

**Comment by anxolin** [comment]
Proposal for the balances page: 
image

**Comment by anxolin** [comment]
Superseded by #852

**Pull request closed without merging**
