### PR TITLE
Feature/orders panel design

### PR DESCRIPTION
**Pull request by biocom**
Need assistance with:
- On click of the orders panel toggle (left arrow) we need to toggle the class '.expanded' on one of the parent widgets. Can provide details.

**Todo:**
- Optimise the orders panel view on mobile (perhaps a overflow-x: auto solution)
- On mobile when clicking on the ORDERS nav item, and then switching to desktop, you remain on the orders page. Need to review.

Screenshot 2020-02-20 at 17 57 19

Screenshot 2020-02-20 at 17 52 45
Screenshot 2020-02-20 at 17 52 39

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr582--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
> On click of the orders panel toggle (left arrow) we need to toggle the class '.expanded' on one of the parent widgets. Can provide details.

I can help with that. Let me PR your branch :)

**Comment by anxolin** [comment]
I like the TODO, maybe you could make separate PRs for them.

By the way. It looks great!!

**Comment by anxolin** [comment]
Maybe is just me, but I was confused at first when I click in this icon to see what happens, and then it tried to send the transaction:

image

I think we should only make clickable the button "Cancel orders" instead of the whole banner.

**Comment by biocom** [comment]
@anxolin Agree. Perhaps better in hindsight.

**Comment by biocom** [comment]
@anxolin Refactored the button now. Also merged in the latest from `develop` and should be good to merge.

**Pull request merged**
