### PR TITLE
Trying stuff for WC connection

### PR DESCRIPTION
**Pull request by Velenir**

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr258--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
Much better!

- tokens are loading
- approve worked

I'm getting this error in the console.
image

Do we have source maps enabled? cause this stacks are a bit not informative

**Comment by anxolin** [comment]
Do we want to keep this logs? 

image

I believe @alfetopito removed them, but maybe was not merged yet.

**Comment by anxolin** [comment]
Deposits work pretty well, but I found an issue if you send more than 1 tx at once!

1. Click approve token A
2. Click approve token B
3. In Gnosis Safe. Try to approve both. They will fail:

IMG_2259


image

**Comment by anxolin** [comment]
Trade worked nicely!

**Comment by alfetopito** [comment]
> Do we want to keep this logs?
> 
> image
> 
> I believe @alfetopito removed them, but maybe was not merged yet.

I removed the most annoying logs, not all of them.

**Comment by Velenir** [comment]
> Do we have source maps enabled? cause this stacks are a bit not informative

we do, the lib this error originates from doesn't

**Comment by Velenir** [comment]
> Do we want to keep this logs?

We do want at least some logs

**Comment by Velenir** [comment]
> Deposits work pretty well, but I found an issue if you send more than 1 tx at once!

This is interesting. Will look into it after the main problem is fixed, if the issue remains.
Could be a good test for QA, though

**Comment by Velenir** [comment]
Closed in favor of #285

**Pull request closed without merging**
