### PR TITLE
Dark colors / Footer behaviour

### PR DESCRIPTION
**Pull request by Velenir**
Proper colors for dark mode

Left to style:

- react-select component ([this can be useful](https://github.com/JedWatson/react-select/issues/3692#issuecomment-523425096))
- web3connect/WalletConnect modals
- probably more minor stuff

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr373--dexreact.review.gnosisdev.com

**Comment by W3stside** [comment]
@anxolin @Velenir @alfetopito what do you guys think of setting `auto` to user's computer clock? e.g after 18h and before 0800 it turns on dark mode?

**Comment by W3stside** [comment]
> @anxolin @Velenir @alfetopito what do you guys think of setting `auto` to user's computer clock? e.g after 18h and before 0800 it turns on dark mode?

actually i just made it, if it sucks we can just remove it easy peasy. everything is persisted as well. yey

**Comment by anxolin** [comment]
> @anxolin @Velenir @alfetopito what do you guys think of setting auto to user's computer clock? e.g after 18h and before 0800 it turns on dark mode?

I thought the auto was taking that from the system. Anyways, I don't have any opinion on this.

I think this PR does more things than it says in the description. I would vote against the new footer being in a fixed position and having this collapse button. Imo it was fine being there when you scroll at the bottom of the page

**Comment by W3stside** [comment]
> > @anxolin @Velenir @alfetopito what do you guys think of setting auto to user's computer clock? e.g after 18h and before 0800 it turns on dark mode?
> 
> I thought the auto was taking that from the system. Anyways, I don't have any opinion on this.
> 
> I think this PR does more things than it says in the description. I would vote against the new footer being in a fixed position and having this collapse button. Imo it was fine being there when you scroll at the bottom of the page

oooh. uh oh then i may have messed up @Velenir's work, all good i can revert if that was the intention. let me know. and yeah I'll move the footer back to unfixed :+1:

**Comment by anxolin** [comment]
Cool, thanks. Mark me again for review whenever u need another eye on it

**Comment by anxolin** [comment]
I think he was using `prefers-color-scheme` media query

**Comment by alfetopito** [comment]
> @anxolin @Velenir @alfetopito what do you guys think of setting `auto` to user's computer clock? e.g after 18h and before 0800 it turns on dark mode?

Personally I don't like that. I would prefer something more subtle like uniswap.exchange:

Screenshot_20200103_071748

**Comment by W3stside** [comment]
> > @anxolin @Velenir @alfetopito what do you guys think of setting `auto` to user's computer clock? e.g after 18h and before 0800 it turns on dark mode?
> 
> Personally I don't like that. I would prefer something more subtle like uniswap.exchange:
> 
> Screenshot_20200103_071748

ok, reverting the `auto` change - I'll leave it up to you guys and @leafilipo on the toggle look

**Pull request merged**
